In [1]:
import numpy as np
import re

In [2]:
f = open("book-war-and-peace.txt")
t = f.readlines()
t = ''.join(t)

In [3]:
text = re.sub('[^a-zA-Z]', ' ', t)[:50000]
text = text.lower()

In [4]:
d = {}
for i in range(0, 26):
    d[chr(i+97)] = i
d[' '] = 26

In [5]:
V = np.zeros(50000)
for i in range(len(text)):
    V[i] = d[text[i]]

In [6]:
V = V.astype(int)
print(V)

[ 2  7  0 ...  8 13  6]


In [7]:
# Transition Probabilities
a = np.array([[0.47468,0.52532],[0.51656,0.48344]])
print(a)

[[0.47468 0.52532]
 [0.51656 0.48344]]


In [8]:
b = np.array([[0.03735,0.03909 ],
[0.03408 ,0.03537 ],
[0.03455 ,0.03537 ],
[0.03828, 0.03909 ],
[0.03782, 0.03583 ],
[0.03922 ,0.03630 ],
[0.03688, 0.04048 ],
[0.03408, 0.03537 ],
[0.03875 ,0.03816 ],
[0.04062 ,0.03909 ],
[0.03735 ,0.03490 ],
[0.03968, 0.03723 ],
[0.03548 ,0.03537 ],
[0.03735 ,0.03909 ],
[0.04062, 0.03397 ],
[0.03595, 0.03397 ],
[0.03641, 0.03816 ],
[0.03408, 0.03676 ],
[0.04062 ,0.04048 ],
[0.03548, 0.03443 ],
[0.03922, 0.03537 ],
[0.04062 ,0.03955], 
[0.03455, 0.03816 ],
[0.03595, 0.03723 ],
[0.03408,0.03769 ],
[0.03408 ,0.03955 ],
[0.03688, 0.03397 ]])
b = b.T
print(b.shape)

(2, 27)


In [9]:
# Equal Probabilities for the initial distribution
initial_distribution = np.array([0.4,0.6])
print(initial_distribution)

[0.4 0.6]


In [10]:
print(V.shape)
print(a.shape)
print(b.shape)
print(V.shape[0], a.shape[0])

(50000,)
(2, 2)
(2, 27)
50000 2


In [11]:
print(b)
print(V)

[[0.03735 0.03408 0.03455 0.03828 0.03782 0.03922 0.03688 0.03408 0.03875
  0.04062 0.03735 0.03968 0.03548 0.03735 0.04062 0.03595 0.03641 0.03408
  0.04062 0.03548 0.03922 0.04062 0.03455 0.03595 0.03408 0.03408 0.03688]
 [0.03909 0.03537 0.03537 0.03909 0.03583 0.0363  0.04048 0.03537 0.03816
  0.03909 0.0349  0.03723 0.03537 0.03909 0.03397 0.03397 0.03816 0.03676
  0.04048 0.03443 0.03537 0.03955 0.03816 0.03723 0.03769 0.03955 0.03397]]
[ 2  7  0 ...  8 13  6]


In [12]:
#defining states and sequence symbols
states = ['H','C']
states_dic = {'H':0, 'C':1}
sequence_syms = {'0':0,'1':1,'2':2,'3':3,'4':4,'5':5,'6':6,'7':7,'8':8,'9':9,'10':10,'11':11,'12':12,'13':13,'14':14,'15':15,'16':16,'17':17,'18':18,'19':19,'20':20,'21':21,'22':22,'23':23,'24':24,'25':25,'26':26}
sequence = ['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26']

#test sequence
temp = ""
for i in V:
    temp = temp + str(i)
test_sequence = temp
test_sequence = [x for x in test_sequence]

In [13]:
print(test_sequence)

['2', '7', '0', '1', '5', '1', '9', '4', '1', '7', '2', '6', '8', '2', '6', '2', '6', '2', '6', '2', '2', '4', '1', '1', '1', '1', '2', '6', '2', '6', '1', '5', '1', '7', '8', '1', '3', '2', '4', '2', '6', '2', '6', '1', '8', '1', '4', '2', '6', '6', '4', '1', '3', '1', '4', '0', '2', '6', '0', '1', '3', '3', '2', '6', '1', '1', '2', '0', '2', '2', '0', '2', '6', '0', '1', '7', '4', '2', '6', '1', '3', '1', '4', '2', '2', '2', '6', '9', '2', '0', '1', '8', '1', '9', '2', '6', '5', '0', '1', '2', '8', '1', '1', '2', '4', '2', '6', '4', '1', '8', '1', '9', '0', '1', '9', '4', '1', '8', '2', '6', '1', '4', '5', '2', '6', '1', '9', '7', '4', '2', '6', '1', '2', '0', '1', '4', '1', '3', '0', '1', '5', '0', '1', '7', '1', '9', '4', '1', '8', '2', '6', '2', '6', '1', '2', '0', '1', '9', '2', '6', '8', '2', '6', '2', '2', '0', '1', '7', '1', '3', '2', '6', '2', '4', '1', '4', '2', '0', '2', '6', '2', '6', '8', '5', '2', '6', '2', '4', '1', '4', '2', '0', '2', '6', '3', '1', '4', '1', '3', '2',

In [14]:
transition = a
#Emission probabilities
emission = b

In [15]:
#probabilities of going to end state
end_probs = [0.0, 1.0]#probabilities of going from start state
start_probs = [0.4,0.6]

In [16]:
#function to find forward probabilities
def forward_probs():
    # node values stored during forward algorithm
    node_values_fwd = np.zeros((len(states), len(test_sequence)))

    for i, sequence_val in enumerate(test_sequence):
        for j in range(len(states)):
            # if first sequence value then do this
            if (i == 0):
                node_values_fwd[j, i] = start_probs[j] * emission[j, sequence_syms[sequence_val]]
            # else perform this
            else:
                values = [node_values_fwd[k, i - 1] * emission[j, sequence_syms[sequence_val]] * transition[k, j] for k in
                          range(len(states))]
                node_values_fwd[j, i] = sum(values)

    #end state value
    end_state = np.multiply(node_values_fwd[:, -1], end_probs)
    end_state_val = sum(end_state)
    return node_values_fwd, end_state_val

In [17]:
#function to find backward probabilities
def backward_probs():
    # node values stored during forward algorithm
    node_values_bwd = np.zeros((len(states), len(test_sequence)))

    #for i, sequence_val in enumerate(test_sequence):
    for i in range(1,len(test_sequence)+1):
        for j in range(len(states)):
            # if first sequence value then do this
            if (-i == -1):
                node_values_bwd[j, -i] = end_probs[j]
            # else perform this
            else:
                values = [node_values_bwd[k, -i+1] * emission[k, sequence_syms[test_sequence[-i+1]]] * transition[j, k] for k in range(len(states))]
                node_values_bwd[j, -i] = sum(values)

    #start state value
    start_state = [node_values_bwd[m,0] * emission[m, sequence_syms[test_sequence[0]]] for m in range(len(states))]
    start_state = np.multiply(start_state, start_probs)
    start_state_val = sum(start_state)
    return node_values_bwd, start_state_val

In [19]:
#function to find si probabilities
def si_probs(forward, backward, forward_val):

    si_probabilities = np.zeros((len(states), len(test_sequence)-1, len(states)))

    for i in range(len(test_sequence)-1):
        for j in range(len(states)):
            for k in range(len(states)):
                si_probabilities[j,i,k] = ( forward[j,i] * backward[k,i+1] * transition[j,k] * emission[k,sequence_syms[test_sequence[i+1]]] ) //forward_val
                                 
    return si_probabilities

In [20]:
def gamma_probs(forward, backward, forward_val):

    gamma_probabilities = np.zeros((len(states), len(test_sequence)))

    for i in range(len(test_sequence)):
        for j in range(len(states)):
            #gamma_probabilities[j,i] = ( forward[j,i] * backward[j,i] * emission[j,sequence_syms[test_sequence[i]]] ) / forward_val
            gamma_probabilities[j, i] = (forward[j, i] * backward[j, i]) / forward_val

    return gamma_probabilities

In [ ]:
for iteration in range(50000):

    print('\nIteration No: ', iteration + 1)
    # print('\nTransition:\n ', transition)
    # print('\nEmission: \n', emission)

    #Calling probability functions to calculate all probabilities
    fwd_probs, fwd_val = forward_probs()
    bwd_probs, bwd_val = backward_probs()
    si_probabilities = si_probs(fwd_probs, bwd_probs, fwd_val)
    gamma_probabilities = gamma_probs(fwd_probs, bwd_probs, fwd_val)

    print('Forward Probs:')
    print(np.matrix(fwd_probs))
    
    print('Backward Probs:')
    print(np.matrix(bwd_probs))
    
    print('Si Probs:')
    print(si_probabilities)
    
    print('Gamma Probs:')
    print(np.matrix(gamma_probabilities))

    #caclculating 'a' and 'b' matrices
    a = np.zeros((len(states), len(states)))
    b = np.zeros((len(states), len(sequence_syms)))

    #'a' matrix
    for j in range(len(states)):
        for i in range(len(states)):
            for t in range(len(test_sequence)-1):
                a[j,i] = a[j,i] + si_probabilities[j,t,i]
                
            denomenator_a = [si_probabilities[j, t_x, i_x] for t_x in range(len(test_sequence) - 1) for i_x in range(len(states))]
            denomenator_a = sum(denomenator_a)
            print(denomenator_a,a[j,i])    
            if (denomenator_a == 0):
                a[j,i] = 0
            else:
                a[j,i] = a[j,i]/denomenator_a

    #'b' matrix
    for j in range(len(states)): #states
        for i in range(len(sequence)): #seq
            indices = [idx for idx, val in enumerate(test_sequence) if val == sequence[i]]
            numerator_b = sum( gamma_probabilities[j,indices] )
            denomenator_b = sum( gamma_probabilities[j,:] )

            if (denomenator_b == 0):
                b[j,i] = 0
            else:
                b[j, i] = numerator_b / denomenator_b


    print('\nMatrix a:\n')
    print(np.matrix(a.round(decimals=4)))
    print('\nMatrix b:\n')
    print(np.matrix(b.round(decimals=4)))

    transition = a
    emission = b

    new_fwd_temp, new_fwd_temp_val = forward_probs()
    print('New forward probability: ', new_fwd_temp_val)
    diff =  np.abs(fwd_val - new_fwd_temp_val)
    print('Difference in forward probability: ', diff)

    if (diff < 0.0000001):
        break

# print('\nMatrix a:\n')
# print(np.matrix(a.round(decimals=4)))
# print('\nMatrix b:\n')
# print(np.matrix(b.round(decimals=4)))
# print('New forward probability: ', new_fwd_temp_val)
# print('Difference in forward probability: ', diff)
c = 1


Iteration No:  1


C:\Users\Mayank Bazari\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in double_scalars
  if __name__ == '__main__':
C:\Users\Mayank Bazari\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in double_scalars
  


Forward Probs:
[[1.38200000e-02 5.97167274e-04 2.25428582e-05 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [2.12220000e-02 6.19664223e-04 2.39728957e-05 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]
Backward Probs:
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 7.88258231e-04
  2.12649536e-02 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 7.90312226e-04
  1.95696512e-02 1.00000000e+00]]
Si Probs:
[[[nan nan]
  [nan nan]
  [nan nan]
  ...
  [nan nan]
  [nan nan]
  [nan nan]]

 [[nan nan]
  [nan nan]
  [nan nan]
  ...
  [nan nan]
  [nan nan]
  [nan nan]]]
Gamma Probs:
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
nan nan
nan nan
nan nan
nan nan

Matrix a:

[[nan nan]
 [nan nan]]

Matrix b:

[[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]]
New forward probabi